language: node_js
<<<<<<< Updated upstream
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database events-manager-test;' -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
- npm run build
- sequelize db:migrate
- sequelize db:seed:all
script: npm test
after_success: npm run coverage
=======

node_js: "stable"

install:
- npm install

script:
- npm test

env:
- NODE_ENV=test

cache:
directories:
- "node_modules"

services:
- postgresql


before_script:
- createuser process.env.MY_NAME -s -U postgres
- createdb process.env.DB_TEST_NAME--process.env.DB_USER=process.env.MY_NAME
- sequelize db:migrate

params:
- .env

after_success: npm run coverage  //scripts in package.json

>>>>>>> Stashed changes
