language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
  global:
- NODE_ENV=test
- secure: XwuNJ93tLENTtuib0+ueVGhyw1gLsB2mXd/YJQbRXdMGt2ebJNCSYvJzt7LF9TtNREr8alyeUDI8Xr/oJxlOBdMS0UWUNJguo45Iy4gpdvA3VLtScJrNOivnZuFGh5n4S9e7Rkmnw7QbjZmZXWEP94q4xe2AvcvEkEAUEk0oOrl2NflCHhiC9HGleULiklhLj4OxTzn6fWJ2BTa72F2VopbNd4pLYY1cSyc4Y9XzojP07IpDhLVKEBdu9No8M9KxD4sn6JfjHM9UZaD02veQVKKLpGU3QPd3OZQlCGMmd2IvimIXbPKKvSjXzezn0WblF5RnS0zgH5KPGpJY2f+VP5dB1PuVpvdDEM2jh0njf27BNpF52VbvBTc769LfCwFI5TOz6o09EbpSXb2DoCAw+XIhUHBMdqWBPAymlaznU0+eVtQ1SKHnEeqxVcjbSUKztYhcuMgXgWlVUgQ4K0fDalXZ8XnkSsvcBq/CrWUGnbhyTfTTO1qBcJtvIhiYv/357aKULwgFSpS6IJXxrTuNJibwjyZeNI3+Ovy2pt/LP1nHmpvnK5vxMzlBzoZfjG6nYS/E2NM0cFTJJTpxrZa48geFvfov37HI0PJUybctLhHsLtmB0VynMhBwd6HKtPS9gHu2QIB/N+ECoA/BMUWpWPW4BN1rA8Px9eCzMCrxKp8=
before_script:
- psql -c 'create database events_manager_test;' -U postgres

- npm run build
- sequelize db:migrate

script: npm test
after_success: npm run coverage
