language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
before_script:
- psql -c 'create database events_manager_test;' -U postgres
- sequelize db:migrate

script: npm test
after_success: npm run coverage
