language: node_js
node_js:
- stable
install: npm install
services:
- postgresql
before_script:
- psql -c 'create database events_manager_test;' -U postgres
- npm run build
- sequelize db:migrate
env:
  global:
     secure: UAY+fpzA1ifDro4Njkinry1PafLZynU/XqDgvxUuZU6fcMUcYTzCRn2crXyZln/yCuaaRnInefwaoRgNvdv+a7PZnTa7xX+xCTgf379Gg3xGM6ALsw7vjtG2QQd0r4ZDlZa2Z/R4qPS8msM6sjggpv8/91soDQtCNaEVdtJyjTqVYv66YxLfIkonX++x+1rSHLouZlrAjrUyGFmhL4U1UHPT2dfA/tE0YQfiqVRSeHnXNkdAHMUtNApNqwAN04Nt55HLIG2PsHo5MtFDnga+h/KrCxfzs1RnCvyoAAtvsESM9vvIfaoP1xxJah34sXAFpWd37075fSI3VxdkIIk/Udc7eKq8WTgpj1ssGnDcv4MGu1gjqmqKiXp9xV7XdiG+uPB1a7ByFAAKMR4XRIHfyOvMSJR2cIeg0DKRlvaZiIRUldv53E/cKT9CwLLskWLNpHSbArIWdi5ipTLJ+zsDkG9lTj98BUrmSNhj5y/KNSwwB26p7mmIDF6vLmOJT81CfVNL4i+pf8X4qfXRzeo5JWlj2Cd/eC6tP0PEJ6xtUCayCGYXTUZ+pq4taz/tdBI9AVICFJJFuph9ttjvyP5i1CBq4k1B4IDSnHxCgoqpTMDn5Cw5Kt0YQRAxdaVOvqXPPA+h1zq/bveGbXfcMQpBtZ2qvUN8OpKvmZVb/n1FvRc=
  matrix:
     secure: UAY+fpzA1ifDro4Njkinry1PafLZynU/XqDgvxUuZU6fcMUcYTzCRn2crXyZln/yCuaaRnInefwaoRgNvdv+a7PZnTa7xX+xCTgf379Gg3xGM6ALsw7vjtG2QQd0r4ZDlZa2Z/R4qPS8msM6sjggpv8/91soDQtCNaEVdtJyjTqVYv66YxLfIkonX++x+1rSHLouZlrAjrUyGFmhL4U1UHPT2dfA/tE0YQfiqVRSeHnXNkdAHMUtNApNqwAN04Nt55HLIG2PsHo5MtFDnga+h/KrCxfzs1RnCvyoAAtvsESM9vvIfaoP1xxJah34sXAFpWd37075fSI3VxdkIIk/Udc7eKq8WTgpj1ssGnDcv4MGu1gjqmqKiXp9xV7XdiG+uPB1a7ByFAAKMR4XRIHfyOvMSJR2cIeg0DKRlvaZiIRUldv53E/cKT9CwLLskWLNpHSbArIWdi5ipTLJ+zsDkG9lTj98BUrmSNhj5y/KNSwwB26p7mmIDF6vLmOJT81CfVNL4i+pf8X4qfXRzeo5JWlj2Cd/eC6tP0PEJ6xtUCayCGYXTUZ+pq4taz/tdBI9AVICFJJFuph9ttjvyP5i1CBq4k1B4IDSnHxCgoqpTMDn5Cw5Kt0YQRAxdaVOvqXPPA+h1zq/bveGbXfcMQpBtZ2qvUN8OpKvmZVb/n1FvRc=
script: npm test
after_success: npm run coverage
