language: node_js
node_js:
- stable
install: npm install
services:
- postgresql
before_script:
- psql -c 'create database events_manager_test;' -U postgres
- npm run build
- sequelize db:migrate
env:
secure: "tXLsWZSXwwdIyeADHvCBjNxl9ZkPtbDZDDWktoxKGsfZ5/NFB7qchvLJ9lZfBuq/RX7HoHK6HgEwecwov4EaQIF7Rjy+FfeMYVOc65gowKq+iBFuoPtkKVBCpNsxZnMh9RL2uXACeQUMPzLFzIFfyZBvcfXpD8nT2eSA/6l6Gz3X2/0EFbxXubO8O+Vy8PrSXdYm1NYoA3rmhT1qRtkvJGnBjrifI7If7zsdOeZ15pacd5THt868SW4ocxVGu2rXYCWyQlxS6Vr2jQRAUnae6EKaL9LQksZ6TxMVuTUMdxpV8u+sTrsDTlLmqM9B1PGQBn+Jju00KX6hwzhVLpxyWP0oM3gu/YKau6dan8KFwMjdPglCi+DWFSdeI1A/AzKd4NqiDpP/D4iGfFLt4NXR9VO/IkEI/w6nK7m0SkAqPRYJ/3ZngIeWQDFHyNpa9bIXajLYzunMacgRWOedrdF1bV6WGfRi1PAChTBstyyTKXE6dbcjdfLo0Z9Q9dnuR7XVIRrVk0YOt/tMVbIzQlmJKUeCa210gYnOK/IZ2Jdo3qS0QdkKsj67FGmVTRNvmwLzQOKMH6H7q7b/+KQJKMKjovn4xFdvq9P/BD6tLevac8+lDy/zsQAs5FOTgwn6Z6GSFJ63qC4OEbxkYI6lcclEjeufWdUc3Iog8NiOQMdCLsk="
script: npm test
after_success: npm run coverage
