language: node_js
node_js:
- stable
install: npm install
services:
- postgresql
before_script:
- psql -c 'create database events_manager_test;' -U postgres
- npm run build
- sequelize db:migrate
script: npm test
after_success: npm run coverage
env:
  secure: aZ4qZyyr7aspV2CImMsVT4RHzZcVCOIwxrao95G5EhlcyUrbma7dsNkas0qhoRk96YcIx9l1oYT7Ms9MdxOW3gBbKZR46yQaY0SKTfv1t3r7Bt9N2OfDkwS+7oiMIBSsBBVv0eUz2zyHkdV8BAWpdEKUqJDJKPi6a9EVXIH7KzL7YEnDPcLCzKTLlZre8Lrn15tRu9pmfkwIk1km0i29zZHW1tbAQGNTOygVzVlBlEWVySnMdMiTIZSBMSgxKCupCgTP53quHqP2FKM4xi27mEKeetuPtqhsh2QWcgRFiN+MBk+xwXMG/auCcSHPIYshr4FJUZ96nuG+YItt7x6+89ol5j8AWsR9geI1R/3JjPWHmQKIIVMpycG61YaBTPjfRc0MX/wy40hxSj1WdJXa+2rJ8r5io+6Xbbjz1+Hsqlw/GOqwRMMz1elrHkRT7D0ZdiwE5j2d2xfTUv6Sv2fdQN2B/vvcKlhB88GdVOYnDj8UWK05Q31T1QKvSxlLLLObCVByEeTUu3l8ff2AGH9QOOl1AvqU+bErVUjhj6zSTJ276cDyBwQmE92U3jhBaDVEXkcUUMRvRrBiaEKSlpjWki62OLFs5Ag38s58+PGVxX1bYCzCB5bvzVuBD3lOyV82vZg2NPzODGKDh9ZTDxcTo28ZZ/+LfBtgU5G6cZiWEtc=
