language: node_js
node_js:
- "stable"
install: npm install
services:
- postgresql
env:
- NODE_ENV=test
before_script:
- psql -c 'create database process.env.DB_TEST_NAME;' -U postgres
- psql -c "CREATE USER postgres WITH PASSWORD process.env.DB_PASSWORD;" -U postgres
- npm run build
- sequelize db:migrate
- sequelize db:seed:all
params: 
- .env
script: npm test
after_success: npm run coverage

